package io.github.lordscales91.magic9;

public enum HackingStep {
	DECRYPT9_BROWSER, DECRYPT9_MSET, DECRYPT9_HOMEBREW, HOMEBREW_SOUNDHAX,
	NFIRM_DOWNGRADE, CTRTRANSFER_210, REQUIRES_UPDATE, INSTALL_ARM9LOADERHAX;
}
